/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductDto { 
    id?: number;
    name: string;
    description?: string | null;
    price?: number;
    deposit?: number;
    volymInml?: number | null;
    pricePerLiter?: number;
    salesStart?: string;
    discontinued?: boolean | null;
    productGroupName?: string | null;
    type?: string | null;
    style?: string | null;
    packaging?: string | null;
    sealType?: string | null;
    origin?: string | null;
    originCountryName?: string | null;
    producerName?: string | null;
    supplierName?: string | null;
    vintage?: number | null;
    alcoholContent?: number;
    assortmentCode?: string | null;
    assortmentText?: string | null;
    organic?: boolean | null;
    ethical?: boolean | null;
    kosher?: boolean | null;
    rawMaterialsDescription?: string | null;
}

